# Site settings
title: Yajun's Home Page
email: fuyajun1983cn@163.com
description: "Copyright Â© 2016 All Rights Reserved" 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
github_username:  fuyajun1983cn
wemedia_username: fuyajun1983cn

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Fu Yajun's Resume"
resume_title:                   "Sofeware Engineer"
resume_contact_email: "fuyajun1983cn@163.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/fuyajun1983cn"
  #resume_twitter_url:           ""
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://ifyj.com"

# Design settings
resume_theme:                   default